# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-13 05:31
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='轮播图片')),
                ('index', models.IntegerField(default=0, verbose_name='轮播顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播商品',
                'verbose_name_plural': '轮播商品',
            },
        ),
        migrations.CreateModel(
            name='HotSearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='热搜词', max_length=20, verbose_name='热搜词')),
                ('index', models.IntegerField(default=0, verbose_name='排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '热搜词',
                'verbose_name_plural': '热搜词',
            },
        ),
        migrations.CreateModel(
            name='Scenic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='景点名称')),
                ('scenic_sn', models.CharField(default='xxx', max_length=50, verbose_name='景点编号')),
                ('lable', models.TextField(default='标签', verbose_name='景点标签')),
                ('province', models.CharField(max_length=20, verbose_name='所在省份')),
                ('city', models.CharField(max_length=20, verbose_name='所在城市')),
                ('address', models.CharField(max_length=100, verbose_name='详细地址')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('visit_num', models.IntegerField(default=0, verbose_name='历史旅游人数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('price', models.FloatField(default=0, verbose_name='平均消费')),
                ('goods_brief', models.TextField(max_length=500, verbose_name='景点简短描述')),
                ('goods_desc', DjangoUeditor.models.UEditorField(default='', verbose_name='景点详细描述')),
                ('is_ticket', models.BooleanField(default=False, verbose_name='是否需要门票')),
                ('goods_front_image', models.ImageField(blank=True, null=True, upload_to='scenic/images/', verbose_name='封面图')),
                ('is_recommend', models.BooleanField(default=False, help_text='是否推荐', verbose_name='是否推荐')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点',
            },
        ),
        migrations.CreateModel(
            name='ScenicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='scenic/images', verbose_name='图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scenic.Scenic', verbose_name='景点')),
            ],
            options={
                'verbose_name': '景点图片',
                'verbose_name_plural': '景点图片',
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenic.Scenic', verbose_name='景点'),
        ),
    ]
