# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-13 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播景点', 'verbose_name_plural': '轮播景点'},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='goods',
            new_name='scenic',
        ),
        migrations.RenameField(
            model_name='scenic',
            old_name='goods_brief',
            new_name='scenic_brief',
        ),
        migrations.RenameField(
            model_name='scenic',
            old_name='goods_desc',
            new_name='scenic_desc',
        ),
        migrations.RenameField(
            model_name='scenic',
            old_name='goods_front_image',
            new_name='scenic_front_image',
        ),
        migrations.RenameField(
            model_name='scenicimage',
            old_name='goods',
            new_name='scenic',
        ),
    ]
