# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-13 05:31
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('article_sn', models.CharField(default='xxx', max_length=50, verbose_name='文章编号')),
                ('lable', models.TextField(default='标签', verbose_name='文章标签')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('article_brief', models.TextField(max_length=500, verbose_name='简短描述')),
                ('article_desc', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('article_front_image', models.ImageField(blank=True, null=True, upload_to='scenic/images/', verbose_name='封面图')),
                ('is_recommend', models.BooleanField(default=False, help_text='是否推荐', verbose_name='是否推荐')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '路书',
                'verbose_name_plural': '路书',
            },
        ),
    ]
